"""sumslice_common.py

Shared paths, loading and text normalisation for the SUMSLICE_LLM evaluation.

Every summary is identified by (project, method_id), the method id of the
original SumSlice input. The reference is the SumSlice (tool) summary in
input/tool_summaries/SUMSLICE_TOOL_SUMMARY.jsonl; candidates are the LLM
summaries in output/SUMSLICE_<MODEL>_SUMMARY.jsonl, generated by the Java
pipeline.

:author: Najam Nazar
:version: 2.0.0
:license: MIT
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Dict, Iterable, List, Tuple

ROOT = Path(__file__).resolve().parent.parent            # SUMSLICE_LLM/
REPO_ROOT = ROOT.parent
INPUT_DIR = ROOT / "input"
OUTPUT_DIR = ROOT / "output"
TOOL_SUMMARY_DIR = INPUT_DIR / "tool_summaries"
RESULTS_DIR = ROOT / "evaluation_results"
PROMPTS_JSON = REPO_ROOT / "resources" / "prompts.json"
ENV_FILE = REPO_ROOT / ".env"

TOOL_FILE = TOOL_SUMMARY_DIR / "SUMSLICE_TOOL_SUMMARY.jsonl"
LLM_SYSTEMS: Dict[str, str] = {
    "CLAUDE": "SUMSLICE_CLAUDE_SUMMARY",
    "GPT": "SUMSLICE_GPT_SUMMARY",
    "MISTRAL": "SUMSLICE_MISTRAL_SUMMARY",
    "QWEN": "SUMSLICE_QWEN_SUMMARY",
}
DISPLAY_NAMES = {"CLAUDE": "Claude", "GPT": "GPT", "MISTRAL": "Mistral", "QWEN": "Qwen"}

Key = Tuple[str, int]


def load_jsonl(path: Path) -> List[dict]:
    if not path.exists():
        return []
    with path.open(encoding="utf-8") as fh:
        return [json.loads(line) for line in fh if line.strip()]


def by_key(rows: Iterable[dict]) -> Dict[Key, dict]:
    out: Dict[Key, dict] = {}
    for r in rows:
        key = (str(r["project"]), int(r["method_id"]))
        if key in out:
            raise ValueError(f"duplicate summary for {key}")
        out[key] = r
    return out


def load_reference() -> Dict[Key, dict]:
    rows = load_jsonl(TOOL_FILE)
    if not rows:
        raise SystemExit(f"{TOOL_FILE} not found; run the Java pipeline (GenerateToolSummaries) first.")
    return by_key(rows)


def load_system(short: str) -> Dict[Key, dict]:
    return by_key(load_jsonl(OUTPUT_DIR / f"{LLM_SYSTEMS[short]}.jsonl"))


def resolve_systems(names) -> List[str]:
    selected = [n.upper() for n in (names or ["ALL"])]
    if selected == ["ALL"]:
        return list(LLM_SYSTEMS)
    unknown = [n for n in selected if n not in LLM_SYSTEMS]
    if unknown:
        raise SystemExit(f"Unknown system(s) {unknown}; choose from ALL, {', '.join(LLM_SYSTEMS)}")
    return selected


_MD = [
    (re.compile(r"```.*?```", re.S), " "),
    (re.compile(r"`([^`]*)`"), r"\1"),
    (re.compile(r"^\s{0,3}#{1,6}\s*", re.M), ""),
    (re.compile(r"^\s*(?:[-*+]|\d+[.)])\s+", re.M), ""),
    (re.compile(r"(\*\*|__)(.*?)\1"), r"\2"),
]


def normalise(text: str) -> str:
    """Same surface form for tool and LLM text: no markdown, lower-case, single spaces."""
    text = text or ""
    for pattern, repl in _MD:
        text = pattern.sub(repl, text)
    return re.sub(r"\s+", " ", text).strip().lower()


def load_prompts() -> dict:
    """The ``sumslice_llm.sumslice-llm`` section of the shared prompts.json.

    The file is shared with PR_LLM and DPS_LLM, so each project's prompts sit
    under its own namespace and, within it, under an alias for the prompt set.
    """
    prompts = json.loads(PROMPTS_JSON.read_text(encoding="utf-8"))["sumslice_llm"]
    return prompts["sumslice-llm"]
