"""evaluate_pr_summaries.py

Compute BERTScore and TF-IDF cosine similarity for PR summaries generated by
pr_llm_summariser.py.

Workflow
--------
1. Read per-model JSONL summary files from the output directory.
2. Batch-compute BERTScore (roberta-large, one call per model label) and
   TF-IDF cosine similarity (sklearn) for every sample.
3. Rewrite each JSONL file with a ``"metrics"`` key added to every record.
4. Write aggregated dataset-level averages to ``results.json``.

Mirrors the evaluation approach used in DPS_LLM's evaluate_summaries.py:
- BERTScore uses the functional API with ``lang='en'`` (roberta-large), batching
  all pairs for a model into one forward pass so the model loads once.
- Cosine similarity uses sklearn TfidfVectorizer + cosine_similarity; no model
  download or load required.

Usage:
    python evaluate_pr_summaries.py [MODEL ...] [options]

    positional:
      MODEL               One or more of: GPT, QWEN, CLAUDE, MISTRAL, ALL
                          Default: ALL

    optional:
      --output DIR        Directory containing JSONL summary files
                          Default: <PR_LLM>/output/
      --limit N           Only evaluate the first N entries per model
      --bertscore-lang S  Language for BERTScore ('en' selects roberta-large)
                          Default: en
      --log-level LEVEL   DEBUG, INFO, WARNING, ERROR  (default: INFO)

:author: Najam Nazar
:version: 1.0.0
:date: 2026-06-22
:license: MIT
"""

from __future__ import annotations

__author__ = "Najam Nazar"
__version__ = "1.0.0"
__date__ = "2026-06-22"
__license__ = "MIT"

import json
import logging
import os
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

# Silence HuggingFace/Transformers output before the heavy libraries are imported.
os.environ.setdefault("TRANSFORMERS_VERBOSITY", "error")
os.environ.setdefault("TOKENIZERS_PARALLELISM", "false")
os.environ.setdefault("HF_HUB_DISABLE_PROGRESS_BARS", "1")
os.environ.setdefault("DISABLE_SAFETENSORS_CONVERSION", "1")

# bert_score functional API — loads roberta-large on first call, batches all
# pairs in one forward pass, matching DPS_LLM's MetricsCalculator.bert_scores.
from bert_score import score as bert_score
from dotenv import load_dotenv
# TF-IDF cosine — matches DPS_LLM's MetricsCalculator.cosine_similarity exactly;
# no model download required.
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity as sklearn_cosine

# Configure logging before any library installs its own handler.
logging.basicConfig(
    level=logging.WARNING,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%H:%M:%S",
)
_console = logging.StreamHandler()
_console.setLevel(logging.INFO)
_console.setFormatter(logging.Formatter("%(asctime)s [%(levelname)s] %(message)s", datefmt="%H:%M:%S"))
logging.getLogger(__name__).addHandler(_console)
logging.getLogger(__name__).setLevel(logging.INFO)
logging.getLogger(__name__).propagate = False
_log = logging.getLogger(__name__)

logging.getLogger("transformers").setLevel(logging.ERROR)
logging.getLogger("sentence_transformers").setLevel(logging.ERROR)
logging.getLogger("bert_score").setLevel(logging.ERROR)
logging.getLogger("httpx").setLevel(logging.WARNING)
logging.getLogger("huggingface_hub").setLevel(logging.ERROR)
try:
    import transformers as _tf
    _tf.logging.set_verbosity_error()
except Exception:
    pass

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
PR_LLM_ROOT = Path(__file__).resolve().parent.parent  # PR_LLM/

_MODEL_ALIASES: Dict[str, str] = {
    "GPT": "PR_GPT_SUMMARY",
    "QWEN": "PR_QWEN_SUMMARY",
    "CLAUDE": "PR_CLAUDE_SUMMARY",
    "MISTRAL": "PR_MISTRAL_SUMMARY",
}


# ---------------------------------------------------------------------------
# Metric helpers
# ---------------------------------------------------------------------------

def _tfidf_cosine(text_a: str, text_b: str) -> float:
    """TF-IDF cosine similarity between two strings (DPS_LLM MetricsCalculator port)."""
    vectorizer = TfidfVectorizer()
    try:
        tfidf = vectorizer.fit_transform([text_a, text_b])
        return float(sklearn_cosine(tfidf[0:1], tfidf[1:2])[0, 0])
    except ValueError:
        # Empty vocabulary — one or both strings are blank or all stop-words.
        return 0.0


# ---------------------------------------------------------------------------
# JSONL helpers
# ---------------------------------------------------------------------------

def _load_jsonl(path: Path, limit: Optional[int] = None) -> List[dict]:
    records: List[dict] = []
    with path.open(encoding="utf-8") as fh:
        for idx, line in enumerate(fh):
            if limit is not None and idx >= limit:
                break
            line = line.strip()
            if line:
                records.append(json.loads(line))
    return records


def _write_jsonl(path: Path, records: List[dict]) -> None:
    with path.open("w", encoding="utf-8") as fh:
        for record in records:
            fh.write(json.dumps(record, ensure_ascii=False) + "\n")


# ---------------------------------------------------------------------------
# Per-model evaluation
# ---------------------------------------------------------------------------

def evaluate_model(
    label: str,
    jsonl_path: Path,
    bert_lang: str,
    device: Optional[str],
    limit: Optional[int],
) -> Dict[str, Optional[float]]:
    """Load a model's JSONL file, compute metrics, rewrite with metrics added.

    Parameters
    ----------
    label:      Full model label (e.g. ``PR_GPT_SUMMARY``).
    jsonl_path: Path to the JSONL file produced by pr_llm_summariser.py.
    bert_lang:  Language code for BERTScore (``'en'`` selects roberta-large).
    device:     Torch device (``None`` = auto-detect).
    limit:      Process only the first *limit* entries.

    Returns
    -------
    Dict with aggregated stats: count, avg_bert_precision, avg_bert_recall,
    avg_bert_f1, avg_cosine_similarity.
    """
    print(f"\n[{label}] Loading {jsonl_path.name} ...", flush=True)
    records = _load_jsonl(jsonl_path, limit)
    n = len(records)
    print(f"[{label}] {n} entries loaded.", flush=True)

    summaries = [r.get("summary", "") for r in records]
    references = [r.get("reference_summary", "") for r in records]

    # Collect non-empty (index, summary, reference) triples for batch BERTScore.
    pairs: List[Tuple[int, str, str]] = [
        (i, s, r)
        for i, (s, r) in enumerate(zip(summaries, references))
        if s
    ]

    bert_by_idx: Dict[int, Tuple[float, float, float]] = {}
    if pairs:
        print(
            f"[{label}] Batch BERTScore — {len(pairs)} non-empty summaries ...",
            flush=True,
        )
        orig_idxs, sums, refs = zip(*pairs)
        P, R, F = bert_score(
            list(sums),
            list(refs),
            lang=bert_lang,
            rescale_with_baseline=False,
            verbose=False,
            device=device,
        )
        for i, p, r, f in zip(orig_idxs, P, R, F):
            bert_by_idx[i] = (float(p.item()), float(r.item()), float(f.item()))

    # Build updated records and collect values for aggregation.
    bp_vals: List[float] = []
    br_vals: List[float] = []
    bf_vals: List[float] = []
    cs_vals: List[float] = []
    updated_records: List[dict] = []

    for idx, record in enumerate(records):
        if idx in bert_by_idx:
            p, r, f = bert_by_idx[idx]
            cosine = _tfidf_cosine(summaries[idx], references[idx])
            record["metrics"] = {
                "bert_precision": p,
                "bert_recall": r,
                "bert_f1": f,
                "cosine_similarity": cosine,
            }
            bp_vals.append(p)
            br_vals.append(r)
            bf_vals.append(f)
            cs_vals.append(cosine)
        else:
            record["metrics"] = {
                "bert_precision": None,
                "bert_recall": None,
                "bert_f1": None,
                "cosine_similarity": None,
            }
        updated_records.append(record)

    # Rewrite JSONL in-place with metrics added.
    _write_jsonl(jsonl_path, updated_records)
    print(f"[{label}] JSONL rewritten with metrics.", flush=True)

    def _avg(vals: List[float]) -> Optional[float]:
        return float(sum(vals) / len(vals)) if vals else None

    stats: Dict[str, object] = {
        "count": len(bf_vals),
        "avg_bert_precision": _avg(bp_vals),
        "avg_bert_recall": _avg(br_vals),
        "avg_bert_f1": _avg(bf_vals),
        "avg_cosine_similarity": _avg(cs_vals),
    }

    avg_p = stats["avg_bert_precision"]
    avg_r = stats["avg_bert_recall"]
    avg_f = stats["avg_bert_f1"]
    avg_c = stats["avg_cosine_similarity"]
    print(
        f"[{label}] BERT P={avg_p:.4f}  R={avg_r:.4f}  F1={avg_f:.4f}  "
        f"cos={avg_c:.4f}  (n={stats['count']})",
        flush=True,
    )
    return stats


# ---------------------------------------------------------------------------
# Violin plot
# ---------------------------------------------------------------------------

# Mirror DPS_LLM's _SHORT_LABEL_COLORS so both studies share a consistent palette.
_MODEL_DISPLAY: Dict[str, str] = {
    "GPT":     "GPT",
    "QWEN":    "Qwen",
    "CLAUDE":  "Claude",
    "MISTRAL": "Mistral",
}

_VIOLIN_COLORS: Dict[str, str] = {
    "GPT":     "#d35400",
    "Qwen":    "#27ae60",
    "Claude":  "#16a085",
    "Mistral": "#2c3e50",
}


def _add_mean_markers(ax: plt.Axes, data: pd.DataFrame, order: List[str], metric: str) -> None:
    """Overlay a red diamond at the mean on each violin body."""
    for idx, model in enumerate(order):
        mean_val = data.loc[data["model"] == model, metric].mean()
        ax.plot(
            idx,
            mean_val,
            marker="D",
            markersize=8,
            color="darkred",
            zorder=3,
            label="Mean" if idx == 0 else "",
        )
    ax.legend(loc="upper left")


def plot_violin_scores(
    output_dir: Path,
    short_names: Optional[List[str]] = None,
    limit: Optional[int] = None,
) -> None:
    """Draw a 1×2 violin plot of BERTScore F1 and cosine similarity for each model.

    Reads per-model JSONL files from *output_dir*, extracts per-record metric
    values, and saves ``violin_scores.png`` to the same directory.  Mirrors the
    style used by DPS_LLM's VisualizationManager: two side-by-side violin panels
    (cosine similarity left, BERTScore F1 right) with a mean-value diamond marker
    overlaid on each violin body.

    Parameters
    ----------
    output_dir:   Directory that contains the JSONL files and will receive the PNG.
    short_names:  Subset of model short names (GPT, QWEN, CLAUDE, MISTRAL) to
                  include.  Defaults to all four.
    limit:        If set, only the first *limit* records per model are used
                  (mirrors the --limit flag used during evaluation).
    """
    if short_names is None:
        short_names = list(_MODEL_ALIASES.keys())

    rows: List[dict] = []
    order: List[str] = []

    for short in short_names:
        label = _MODEL_ALIASES[short]
        path = output_dir / f"{label}.jsonl"
        if not path.exists():
            print(f"[violin] {path.name} not found — skipping {short}", flush=True)
            continue

        records = _load_jsonl(path, limit)
        display = _MODEL_DISPLAY.get(short, short)
        if display not in order:
            order.append(display)

        for rec in records:
            m = rec.get("metrics") or {}
            bf = m.get("bert_f1")
            cs = m.get("cosine_similarity")
            if bf is None or cs is None:
                continue
            rows.append({"model": display, "bert_f1": float(bf), "cosine_similarity": float(cs)})

    if not rows:
        print("[violin] No metric data found — skipping violin plot.", flush=True)
        return

    data = pd.DataFrame(rows)
    palette = {lbl: _VIOLIN_COLORS[lbl] for lbl in order if lbl in _VIOLIN_COLORS}

    sns.set_theme(style="whitegrid")
    fig, axes = plt.subplots(1, 2, figsize=(max(12, len(order) * 2.5), 6))
    fig.suptitle("PR Summary Evaluation: Score Distributions", fontsize=14, fontweight="bold")

    for ax, metric, ylabel, panel_title in (
        (axes[0], "cosine_similarity", "Cosine Similarity Score", "Cosine Similarity"),
        (axes[1], "bert_f1",           "BERTScore F1 Score",      "BERTScore F1"),
    ):
        sns.violinplot(
            data=data,
            x="model",
            y=metric,
            ax=ax,
            order=order,
            palette=palette or None,
            hue="model",
            legend=False,
        )
        ax.set_title(panel_title, fontsize=13, fontweight="bold")
        ax.set_xlabel("Model", fontsize=11)
        ax.set_ylabel(ylabel, fontsize=11)
        ax.grid(axis="y", alpha=0.3)
        _add_mean_markers(ax, data, order, metric)

    plt.tight_layout()
    out_path = output_dir / "violin_scores.png"
    plt.savefig(out_path, dpi=300, bbox_inches="tight")
    plt.close()
    print(f"[violin] Saved: {out_path}", flush=True)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    import argparse

    parser = argparse.ArgumentParser(
        description=(
            "Compute BERTScore and TF-IDF cosine metrics for PR summaries, "
            "update JSONL files, and write aggregated results.json."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "models",
        metavar="MODEL",
        nargs="*",
        default=["ALL"],
        help="One or more of: GPT, QWEN, CLAUDE, MISTRAL, ALL. Default: ALL",
    )
    parser.add_argument(
        "--output", type=Path,
        help="Directory containing JSONL summary files. Default: <PR_LLM>/output/",
    )
    parser.add_argument(
        "--limit", type=int, default=None,
        help="Only evaluate the first N entries per model (useful for testing).",
    )
    parser.add_argument(
        "--bertscore-lang", default="en",
        help="Language for BERTScore — 'en' selects roberta-large (default: en).",
    )
    parser.add_argument(
        "--log-level", default="INFO",
        help="Logging level: DEBUG, INFO, WARNING, ERROR (default: INFO).",
    )
    args = parser.parse_args()

    level = getattr(logging, args.log_level.upper(), logging.INFO)
    _log.setLevel(level)
    _log.handlers[0].setLevel(level)

    load_dotenv(PR_LLM_ROOT.parent / ".env")
    output_dir = args.output or (PR_LLM_ROOT / "output")

    selected = [m.upper() for m in args.models]
    if selected == ["ALL"]:
        short_names = list(_MODEL_ALIASES.keys())
    else:
        unknown = [m for m in selected if m not in _MODEL_ALIASES]
        if unknown:
            raise SystemExit(
                f"Unknown model(s): {unknown}. Valid choices: {list(_MODEL_ALIASES)}"
            )
        short_names = selected

    results: Dict[str, dict] = {}
    for short_name in short_names:
        label = _MODEL_ALIASES[short_name]
        path = output_dir / f"{label}.jsonl"
        if not path.exists():
            _log.warning("[%s] File not found: %s — skipping", short_name, path)
            continue
        stats = evaluate_model(
            label=label,
            jsonl_path=path,
            bert_lang=args.bertscore_lang,
            device=None,
            limit=args.limit,
        )
        results[label] = stats

    if not results:
        _log.error("No JSONL files found to evaluate in %s", output_dir)
        raise SystemExit(1)

    # Merge into existing results.json so rubric_evaluation data is preserved.
    results_path = output_dir / "results.json"
    existing: dict = {}
    if results_path.exists():
        try:
            with results_path.open(encoding="utf-8") as fh:
                existing = json.load(fh)
        except Exception:
            pass
    for label, stats in results.items():
        if label not in existing:
            existing[label] = {}
        existing[label].update(stats)

    with results_path.open("w", encoding="utf-8") as fh:
        json.dump(existing, fh, indent=2)

    print(f"\n[Done] Aggregated results written to: {results_path}", flush=True)

    print("\n[violin] Generating violin plot ...", flush=True)
    plot_violin_scores(output_dir, short_names=short_names, limit=args.limit)

    print("Next: run rank_pr_summaries.py for rubric-based LLM ranking.", flush=True)


if __name__ == "__main__":
    main()
